# version: '3'
# services:
#   postgres:
#     build:
#       context: ./postgres  # Thư mục chứa Dockerfile cho PostgreSQL
#       dockerfile: Dockerfile
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: 1234
#       POSTGRES_DB: gym_app
#     ports:
#       - "5433:5432"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data

#   app:
#     image: hunganhvn/gym-app-backend:config_db
#     build: .
#     environment:
#       DB_HOST: postgres
#       DB_PORT: 5432
#       DB_USERNAME: admin
#       DB_PASSWORD: 1234
#       DB_NAME: gym_app
#       PORT: 3000
#     ports:
#       - "3000:3000"
#     depends_on:
#       - postgres
#     volumes:
#       - .:/app
#     command: npm run start

# volumes:
#   postgres-data:

services:
  postgres:
    image: postgres:16.4
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gym_app
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - gym-network

  app:
    image: hunganhvn/gym-app-backend:config_db
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: 1234
      DB_NAME: gym_app
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - gym-network

volumes:
  postgres-data:
    driver: local

networks:
  gym-network:
    driver: bridge
