version: '3'
services:
  postgres:
    build:
      context: ./postgres  # Thư mục chứa Dockerfile cho PostgreSQL
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: gym_app
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: hunganhvn/gym-app-backend:workout
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: 1234
      DB_NAME: gym_app
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app

volumes:
  postgres-data:

# services:
#   postgres:
#     build:
#       context: ./postgres  # Thư mục chứa Dockerfile cho PostgreSQL
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: 1234
#       POSTGRES_DB: gym_app
#     ports:
#       - "5433:5432"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     networks:
#       - gym-network
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U admin"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   app:
#     image: hunganhvn/gym-app-backend:db2
#     environment:
#       DB_HOST: postgres
#       DB_PORT: 5432
#       DB_USERNAME: admin
#       DB_PASSWORD: 1234
#       DB_NAME: gym_app
#       PORT: 3000
#     ports:
#       - "3000:3000"
#     depends_on:
#       - postgres
#     networks:
#       - gym-network

# volumes:
#   postgres-data:
#     driver: local

# networks:
#   gym-network:
#     driver: bridge
