
GET http://127.0.0.1:3000/api/exercises/list?experience_level=1&target_muscle=3&offset=2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInV1aWQiOiI2MjlhNjdmNy01ZjlmLTQ2MDktYjI4Yi1mYzY0ZmQxZjJkNjAiLCJpYXQiOjE3MzE3NjkzNzAsImV4cCI6MTczMTc4MDE3MH0.BYA8jZBTJ9qA72TA5XTZbu-euBADj0t18cVSh-2Mzfw

###
GET http://127.0.0.1:3000/api/exercises/?exercise_id=1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInV1aWQiOiI2MTg2NzJhZS05MTg2LTRmMmItYjJiYS0xMzNlNjA2ZWFmMjgiLCJpYXQiOjE3MzE3OTI3MzcsImV4cCI6MTczMTgwMzUzN30.Pwg9E3gKgcXiWR_ELIBrogltcysYFHCTGutYAzlaYYU