
# GET http://localhost:3000/api/workouts/list?limit=10&offset=0
# Content-Type: application/json



GET http://localhost:3000/api/workouts/my_plan/4
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsInV1aWQiOiJlZTNjYjYzNC1mZjVkLTQxZmMtYjQ3Mi1mOWY3Yjg3ZDhkOTIiLCJpYXQiOjE3MzI2NzEwOTgsImV4cCI6MTczMjY4MTg5OH0._sF1CM2TAvmPiFYgEP3WsrFiXhuLIZCNCZ81Rbi7Xgw
# {
#     "user_id": "1"
# }

###

GET http://localhost:3000/api/workouts/get/1
Content-Type: application/json

###
GET http://localhost:3000/api/workouts/get_for_card/2
Content-Type: application/json


###
POST http://127.0.0.1:5000/predict
Content-Type: application/json

{
    "gender": 0,
    "fitness_goal": 1,
    "age": 34,
    "bmi": 25.5
}

###
POST http://localhost:3000/api/workouts/create_recommendation
Content-Type: application/json

{
    "gender": 0,
    "fitness_goal": 1,
    "age": 30,
    "bmi": 25.5
}

###